/*
 * SignerenoAddonServices.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/10/2016
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SignerenoAddonServices.PCL;
using SignerenoAddonServices.PCL.Utilities;

namespace SignerenoAddonServices.PCL.Models
{
    public class SignerenoAddonservicesModelsGeneratedCodePersonInfoMeldinger : INotifyPropertyChanged 
    {
        // These fields hold the values for the public properties.
        private int? meldingsKodeField;
        private string meldingsTekstField;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("meldingsKodeField")]
        public int? MeldingsKodeField 
        { 
            get 
            {
                return this.meldingsKodeField; 
            } 
            set 
            {
                this.meldingsKodeField = value;
                onPropertyChanged("MeldingsKodeField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("meldingsTekstField")]
        public string MeldingsTekstField 
        { 
            get 
            {
                return this.meldingsTekstField; 
            } 
            set 
            {
                this.meldingsTekstField = value;
                onPropertyChanged("MeldingsTekstField");
            }
        }

        /// <summary>
        /// Property changed event for observer pattern
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises event when a property is changed
        /// </summary>
        /// <param name="propertyName">Name of the changed property</param>
        protected void onPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
} 