/*
 * SignerenoAddonServices.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/10/2016
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SignerenoAddonServices.PCL;
using SignerenoAddonServices.PCL.Utilities;

namespace SignerenoAddonServices.PCL.Models
{
    public class SignerenoAddonservicesModelsGeneratedCodePersonInfoEiendomListe : INotifyPropertyChanged 
    {
        // These fields hold the values for the public properties.
        private string kommunenrField;
        private string kommuneNavnField;
        private int? gardnrField;
        private int? bruksnrField;
        private int? festenrField;
        private int? seksjonsnrField;
        private string typeField;
        private string andelField;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("kommunenrField")]
        public string KommunenrField 
        { 
            get 
            {
                return this.kommunenrField; 
            } 
            set 
            {
                this.kommunenrField = value;
                onPropertyChanged("KommunenrField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("kommuneNavnField")]
        public string KommuneNavnField 
        { 
            get 
            {
                return this.kommuneNavnField; 
            } 
            set 
            {
                this.kommuneNavnField = value;
                onPropertyChanged("KommuneNavnField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("gardnrField")]
        public int? GardnrField 
        { 
            get 
            {
                return this.gardnrField; 
            } 
            set 
            {
                this.gardnrField = value;
                onPropertyChanged("GardnrField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("bruksnrField")]
        public int? BruksnrField 
        { 
            get 
            {
                return this.bruksnrField; 
            } 
            set 
            {
                this.bruksnrField = value;
                onPropertyChanged("BruksnrField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("festenrField")]
        public int? FestenrField 
        { 
            get 
            {
                return this.festenrField; 
            } 
            set 
            {
                this.festenrField = value;
                onPropertyChanged("FestenrField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("seksjonsnrField")]
        public int? SeksjonsnrField 
        { 
            get 
            {
                return this.seksjonsnrField; 
            } 
            set 
            {
                this.seksjonsnrField = value;
                onPropertyChanged("SeksjonsnrField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("typeField")]
        public string TypeField 
        { 
            get 
            {
                return this.typeField; 
            } 
            set 
            {
                this.typeField = value;
                onPropertyChanged("TypeField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("andelField")]
        public string AndelField 
        { 
            get 
            {
                return this.andelField; 
            } 
            set 
            {
                this.andelField = value;
                onPropertyChanged("AndelField");
            }
        }

        /// <summary>
        /// Property changed event for observer pattern
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises event when a property is changed
        /// </summary>
        /// <param name="propertyName">Name of the changed property</param>
        protected void onPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
} 