/*
 * SignerenoAddonServices.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/10/2016
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SignerenoAddonServices.PCL;
using SignerenoAddonServices.PCL.Utilities;

namespace SignerenoAddonServices.PCL.Models
{
    public class SignerenoAddonservicesModelsGeneratedCodeForetakinfoIdentifikasjon : INotifyPropertyChanged 
    {
        // These fields hold the values for the public properties.
        private int? orgnrField;
        private int? dunsnrField;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("orgnrField")]
        public int? OrgnrField 
        { 
            get 
            {
                return this.orgnrField; 
            } 
            set 
            {
                this.orgnrField = value;
                onPropertyChanged("OrgnrField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("dunsnrField")]
        public int? DunsnrField 
        { 
            get 
            {
                return this.dunsnrField; 
            } 
            set 
            {
                this.dunsnrField = value;
                onPropertyChanged("DunsnrField");
            }
        }

        /// <summary>
        /// Property changed event for observer pattern
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises event when a property is changed
        /// </summary>
        /// <param name="propertyName">Name of the changed property</param>
        protected void onPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
} 