/*
 * SignerenoAddonServices.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/10/2016
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SignerenoAddonServices.PCL;
using SignerenoAddonServices.PCL.Utilities;

namespace SignerenoAddonServices.PCL.Models
{
    public class SignerenoAddonservicesModelsGeneratedCodeForetakinfoLosore : INotifyPropertyChanged 
    {
        // These fields hold the values for the public properties.
        private DateTime? ajourDatoField;
        private string spesTekst1Field;
        private string spesTekst2Field;
        private string spesTekst3Field;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("ajourDatoField")]
        public DateTime? AjourDatoField 
        { 
            get 
            {
                return this.ajourDatoField; 
            } 
            set 
            {
                this.ajourDatoField = value;
                onPropertyChanged("AjourDatoField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("spesTekst1Field")]
        public string SpesTekst1Field 
        { 
            get 
            {
                return this.spesTekst1Field; 
            } 
            set 
            {
                this.spesTekst1Field = value;
                onPropertyChanged("SpesTekst1Field");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("spesTekst2Field")]
        public string SpesTekst2Field 
        { 
            get 
            {
                return this.spesTekst2Field; 
            } 
            set 
            {
                this.spesTekst2Field = value;
                onPropertyChanged("SpesTekst2Field");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("spesTekst3Field")]
        public string SpesTekst3Field 
        { 
            get 
            {
                return this.spesTekst3Field; 
            } 
            set 
            {
                this.spesTekst3Field = value;
                onPropertyChanged("SpesTekst3Field");
            }
        }

        /// <summary>
        /// Property changed event for observer pattern
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises event when a property is changed
        /// </summary>
        /// <param name="propertyName">Name of the changed property</param>
        protected void onPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
} 