/*
 * SignerenoAddonServices.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/10/2016
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SignerenoAddonServices.PCL;
using SignerenoAddonServices.PCL.Utilities;

namespace SignerenoAddonServices.PCL.Models
{
    public class SignerenoAddonservicesModelsGeneratedCodePersonInfoDelomrader : INotifyPropertyChanged 
    {
        // These fields hold the values for the public properties.
        private string delomradeKodeField;
        private string delomradeTekstField;
        private string bedommelseKodeField;
        private string bedommelseTekstField;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("delomradeKodeField")]
        public string DelomradeKodeField 
        { 
            get 
            {
                return this.delomradeKodeField; 
            } 
            set 
            {
                this.delomradeKodeField = value;
                onPropertyChanged("DelomradeKodeField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("delomradeTekstField")]
        public string DelomradeTekstField 
        { 
            get 
            {
                return this.delomradeTekstField; 
            } 
            set 
            {
                this.delomradeTekstField = value;
                onPropertyChanged("DelomradeTekstField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("bedommelseKodeField")]
        public string BedommelseKodeField 
        { 
            get 
            {
                return this.bedommelseKodeField; 
            } 
            set 
            {
                this.bedommelseKodeField = value;
                onPropertyChanged("BedommelseKodeField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("bedommelseTekstField")]
        public string BedommelseTekstField 
        { 
            get 
            {
                return this.bedommelseTekstField; 
            } 
            set 
            {
                this.bedommelseTekstField = value;
                onPropertyChanged("BedommelseTekstField");
            }
        }

        /// <summary>
        /// Property changed event for observer pattern
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises event when a property is changed
        /// </summary>
        /// <param name="propertyName">Name of the changed property</param>
        protected void onPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
} 