/*
 * SignerenoAddonServices.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/10/2016
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SignerenoAddonServices.PCL;
using SignerenoAddonServices.PCL.Utilities;

namespace SignerenoAddonServices.PCL.Models
{
    public class SignerenoAddonservicesModelsGeneratedCodeForetakinfoEiendelerForetak : INotifyPropertyChanged 
    {
        // These fields hold the values for the public properties.
        private int? regnskapsAvArField;
        private int? regnskapsAvMndField;
        private long? sumAnleggsmidlerField;
        private long? sumImmatrielleEiendelerField;
        private long? forskningUtviklingField;
        private long? konsesjonerField;
        private long? utsattSkattefordelField;
        private long? goodwillField;
        private long? sumVarigeDriftsmidlerField;
        private long? fastEiendomField;
        private long? maskinerAnleggField;
        private long? skipRiggFlyField;
        private long? driftsLosoreField;
        private long? sumFinansielleAnleggsmilderField;
        private long? investDatterField;
        private long? investAnnetKonsernField;
        private long? konsernfordringField;
        private long? investTilknyttetField;
        private long? lanTilknyttetField;
        private long? investAksjerField;
        private long? obligasjonerField;
        private long? pensjonsmidlerField;
        private long? andreAnleggsmidlerField;
        private long? sumOmlopsmidlerField;
        private long? sumVarerField;
        private long? lagerRavarerField;
        private long? lagerUferdigeVarerField;
        private long? lagerFerdigeVarerField;
        private long? sumFordringerField;
        private long? fordringerKunderField;
        private long? fordringerAndreField;
        private long? fordringerKonsernField;
        private long? kravInnbetSelskapskapitalField;
        private long? sumInvesteringerField;
        private long? aksjerKonsernField;
        private long? aksjerMarkedField;
        private long? obligasjonerMarkedField;
        private long? andreMarkedFinInvField;
        private long? andreFinInstField;
        private long? bankinnskuddField;
        private long? andreOmlopsmidlerField;
        private long? sumEiendelerField;
        private long? pantstillelserField;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("regnskapsAvArField")]
        public int? RegnskapsAvArField 
        { 
            get 
            {
                return this.regnskapsAvArField; 
            } 
            set 
            {
                this.regnskapsAvArField = value;
                onPropertyChanged("RegnskapsAvArField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("regnskapsAvMndField")]
        public int? RegnskapsAvMndField 
        { 
            get 
            {
                return this.regnskapsAvMndField; 
            } 
            set 
            {
                this.regnskapsAvMndField = value;
                onPropertyChanged("RegnskapsAvMndField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("sumAnleggsmidlerField")]
        public long? SumAnleggsmidlerField 
        { 
            get 
            {
                return this.sumAnleggsmidlerField; 
            } 
            set 
            {
                this.sumAnleggsmidlerField = value;
                onPropertyChanged("SumAnleggsmidlerField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("sumImmatrielleEiendelerField")]
        public long? SumImmatrielleEiendelerField 
        { 
            get 
            {
                return this.sumImmatrielleEiendelerField; 
            } 
            set 
            {
                this.sumImmatrielleEiendelerField = value;
                onPropertyChanged("SumImmatrielleEiendelerField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("forskningUtviklingField")]
        public long? ForskningUtviklingField 
        { 
            get 
            {
                return this.forskningUtviklingField; 
            } 
            set 
            {
                this.forskningUtviklingField = value;
                onPropertyChanged("ForskningUtviklingField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("konsesjonerField")]
        public long? KonsesjonerField 
        { 
            get 
            {
                return this.konsesjonerField; 
            } 
            set 
            {
                this.konsesjonerField = value;
                onPropertyChanged("KonsesjonerField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("utsattSkattefordelField")]
        public long? UtsattSkattefordelField 
        { 
            get 
            {
                return this.utsattSkattefordelField; 
            } 
            set 
            {
                this.utsattSkattefordelField = value;
                onPropertyChanged("UtsattSkattefordelField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("goodwillField")]
        public long? GoodwillField 
        { 
            get 
            {
                return this.goodwillField; 
            } 
            set 
            {
                this.goodwillField = value;
                onPropertyChanged("GoodwillField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("sumVarigeDriftsmidlerField")]
        public long? SumVarigeDriftsmidlerField 
        { 
            get 
            {
                return this.sumVarigeDriftsmidlerField; 
            } 
            set 
            {
                this.sumVarigeDriftsmidlerField = value;
                onPropertyChanged("SumVarigeDriftsmidlerField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("fastEiendomField")]
        public long? FastEiendomField 
        { 
            get 
            {
                return this.fastEiendomField; 
            } 
            set 
            {
                this.fastEiendomField = value;
                onPropertyChanged("FastEiendomField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("maskinerAnleggField")]
        public long? MaskinerAnleggField 
        { 
            get 
            {
                return this.maskinerAnleggField; 
            } 
            set 
            {
                this.maskinerAnleggField = value;
                onPropertyChanged("MaskinerAnleggField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("skipRiggFlyField")]
        public long? SkipRiggFlyField 
        { 
            get 
            {
                return this.skipRiggFlyField; 
            } 
            set 
            {
                this.skipRiggFlyField = value;
                onPropertyChanged("SkipRiggFlyField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("driftsLosoreField")]
        public long? DriftsLosoreField 
        { 
            get 
            {
                return this.driftsLosoreField; 
            } 
            set 
            {
                this.driftsLosoreField = value;
                onPropertyChanged("DriftsLosoreField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("sumFinansielleAnleggsmilderField")]
        public long? SumFinansielleAnleggsmilderField 
        { 
            get 
            {
                return this.sumFinansielleAnleggsmilderField; 
            } 
            set 
            {
                this.sumFinansielleAnleggsmilderField = value;
                onPropertyChanged("SumFinansielleAnleggsmilderField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("investDatterField")]
        public long? InvestDatterField 
        { 
            get 
            {
                return this.investDatterField; 
            } 
            set 
            {
                this.investDatterField = value;
                onPropertyChanged("InvestDatterField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("investAnnetKonsernField")]
        public long? InvestAnnetKonsernField 
        { 
            get 
            {
                return this.investAnnetKonsernField; 
            } 
            set 
            {
                this.investAnnetKonsernField = value;
                onPropertyChanged("InvestAnnetKonsernField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("konsernfordringField")]
        public long? KonsernfordringField 
        { 
            get 
            {
                return this.konsernfordringField; 
            } 
            set 
            {
                this.konsernfordringField = value;
                onPropertyChanged("KonsernfordringField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("investTilknyttetField")]
        public long? InvestTilknyttetField 
        { 
            get 
            {
                return this.investTilknyttetField; 
            } 
            set 
            {
                this.investTilknyttetField = value;
                onPropertyChanged("InvestTilknyttetField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("lanTilknyttetField")]
        public long? LanTilknyttetField 
        { 
            get 
            {
                return this.lanTilknyttetField; 
            } 
            set 
            {
                this.lanTilknyttetField = value;
                onPropertyChanged("LanTilknyttetField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("investAksjerField")]
        public long? InvestAksjerField 
        { 
            get 
            {
                return this.investAksjerField; 
            } 
            set 
            {
                this.investAksjerField = value;
                onPropertyChanged("InvestAksjerField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("obligasjonerField")]
        public long? ObligasjonerField 
        { 
            get 
            {
                return this.obligasjonerField; 
            } 
            set 
            {
                this.obligasjonerField = value;
                onPropertyChanged("ObligasjonerField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("pensjonsmidlerField")]
        public long? PensjonsmidlerField 
        { 
            get 
            {
                return this.pensjonsmidlerField; 
            } 
            set 
            {
                this.pensjonsmidlerField = value;
                onPropertyChanged("PensjonsmidlerField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("andreAnleggsmidlerField")]
        public long? AndreAnleggsmidlerField 
        { 
            get 
            {
                return this.andreAnleggsmidlerField; 
            } 
            set 
            {
                this.andreAnleggsmidlerField = value;
                onPropertyChanged("AndreAnleggsmidlerField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("sumOmlopsmidlerField")]
        public long? SumOmlopsmidlerField 
        { 
            get 
            {
                return this.sumOmlopsmidlerField; 
            } 
            set 
            {
                this.sumOmlopsmidlerField = value;
                onPropertyChanged("SumOmlopsmidlerField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("sumVarerField")]
        public long? SumVarerField 
        { 
            get 
            {
                return this.sumVarerField; 
            } 
            set 
            {
                this.sumVarerField = value;
                onPropertyChanged("SumVarerField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("lagerRavarerField")]
        public long? LagerRavarerField 
        { 
            get 
            {
                return this.lagerRavarerField; 
            } 
            set 
            {
                this.lagerRavarerField = value;
                onPropertyChanged("LagerRavarerField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("lagerUferdigeVarerField")]
        public long? LagerUferdigeVarerField 
        { 
            get 
            {
                return this.lagerUferdigeVarerField; 
            } 
            set 
            {
                this.lagerUferdigeVarerField = value;
                onPropertyChanged("LagerUferdigeVarerField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("lagerFerdigeVarerField")]
        public long? LagerFerdigeVarerField 
        { 
            get 
            {
                return this.lagerFerdigeVarerField; 
            } 
            set 
            {
                this.lagerFerdigeVarerField = value;
                onPropertyChanged("LagerFerdigeVarerField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("sumFordringerField")]
        public long? SumFordringerField 
        { 
            get 
            {
                return this.sumFordringerField; 
            } 
            set 
            {
                this.sumFordringerField = value;
                onPropertyChanged("SumFordringerField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("fordringerKunderField")]
        public long? FordringerKunderField 
        { 
            get 
            {
                return this.fordringerKunderField; 
            } 
            set 
            {
                this.fordringerKunderField = value;
                onPropertyChanged("FordringerKunderField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("fordringerAndreField")]
        public long? FordringerAndreField 
        { 
            get 
            {
                return this.fordringerAndreField; 
            } 
            set 
            {
                this.fordringerAndreField = value;
                onPropertyChanged("FordringerAndreField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("fordringerKonsernField")]
        public long? FordringerKonsernField 
        { 
            get 
            {
                return this.fordringerKonsernField; 
            } 
            set 
            {
                this.fordringerKonsernField = value;
                onPropertyChanged("FordringerKonsernField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("kravInnbetSelskapskapitalField")]
        public long? KravInnbetSelskapskapitalField 
        { 
            get 
            {
                return this.kravInnbetSelskapskapitalField; 
            } 
            set 
            {
                this.kravInnbetSelskapskapitalField = value;
                onPropertyChanged("KravInnbetSelskapskapitalField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("sumInvesteringerField")]
        public long? SumInvesteringerField 
        { 
            get 
            {
                return this.sumInvesteringerField; 
            } 
            set 
            {
                this.sumInvesteringerField = value;
                onPropertyChanged("SumInvesteringerField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("aksjerKonsernField")]
        public long? AksjerKonsernField 
        { 
            get 
            {
                return this.aksjerKonsernField; 
            } 
            set 
            {
                this.aksjerKonsernField = value;
                onPropertyChanged("AksjerKonsernField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("aksjerMarkedField")]
        public long? AksjerMarkedField 
        { 
            get 
            {
                return this.aksjerMarkedField; 
            } 
            set 
            {
                this.aksjerMarkedField = value;
                onPropertyChanged("AksjerMarkedField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("obligasjonerMarkedField")]
        public long? ObligasjonerMarkedField 
        { 
            get 
            {
                return this.obligasjonerMarkedField; 
            } 
            set 
            {
                this.obligasjonerMarkedField = value;
                onPropertyChanged("ObligasjonerMarkedField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("andreMarkedFinInvField")]
        public long? AndreMarkedFinInvField 
        { 
            get 
            {
                return this.andreMarkedFinInvField; 
            } 
            set 
            {
                this.andreMarkedFinInvField = value;
                onPropertyChanged("AndreMarkedFinInvField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("andreFinInstField")]
        public long? AndreFinInstField 
        { 
            get 
            {
                return this.andreFinInstField; 
            } 
            set 
            {
                this.andreFinInstField = value;
                onPropertyChanged("AndreFinInstField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("bankinnskuddField")]
        public long? BankinnskuddField 
        { 
            get 
            {
                return this.bankinnskuddField; 
            } 
            set 
            {
                this.bankinnskuddField = value;
                onPropertyChanged("BankinnskuddField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("andreOmlopsmidlerField")]
        public long? AndreOmlopsmidlerField 
        { 
            get 
            {
                return this.andreOmlopsmidlerField; 
            } 
            set 
            {
                this.andreOmlopsmidlerField = value;
                onPropertyChanged("AndreOmlopsmidlerField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("sumEiendelerField")]
        public long? SumEiendelerField 
        { 
            get 
            {
                return this.sumEiendelerField; 
            } 
            set 
            {
                this.sumEiendelerField = value;
                onPropertyChanged("SumEiendelerField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("pantstillelserField")]
        public long? PantstillelserField 
        { 
            get 
            {
                return this.pantstillelserField; 
            } 
            set 
            {
                this.pantstillelserField = value;
                onPropertyChanged("PantstillelserField");
            }
        }

        /// <summary>
        /// Property changed event for observer pattern
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises event when a property is changed
        /// </summary>
        /// <param name="propertyName">Name of the changed property</param>
        protected void onPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
} 