/*
 * SignerenoAddonServices.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/10/2016
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SignerenoAddonServices.PCL;
using SignerenoAddonServices.PCL.Utilities;

namespace SignerenoAddonServices.PCL.Models
{
    public class SignerenoAddonservicesModelsGeneratedCodeForetakinfoHentForetakResponse : INotifyPropertyChanged 
    {
        // These fields hold the values for the public properties.
        private SignerenoAddonservicesModelsGeneratedCodeForetakinfoIdentifikasjon identifikasjonField;
        private SignerenoAddonservicesModelsGeneratedCodeForetakinfoNavnAdresse navnAdresseField;
        private SignerenoAddonservicesModelsGeneratedCodeForetakinfoRating ratingField;
        private List<SignerenoAddonservicesModelsGeneratedCodeForetakinfoHistoriskRating> histRatingField;
        private SignerenoAddonservicesModelsGeneratedCodeForetakinfoGrunnfakta grunnfaktaField;
        private List<SignerenoAddonservicesModelsGeneratedCodeForetakinfoJuridisk> juridiskField;
        private List<SignerenoAddonservicesModelsGeneratedCodeForetakinfoVerv> vervField;
        private List<SignerenoAddonservicesModelsGeneratedCodeForetakinfoAksjonar> aksjonarField;
        private List<SignerenoAddonservicesModelsGeneratedCodeForetakinfoDatterselskap> datterselskapField;
        private List<SignerenoAddonservicesModelsGeneratedCodeForetakinfoOkonomiEnk> okonomiEnkField;
        private List<SignerenoAddonservicesModelsGeneratedCodeForetakinfoNokkeltallForetak> nokkeltallForetakField;
        private List<SignerenoAddonservicesModelsGeneratedCodeForetakinfoNokkeltallBransje> nokkeltallBransjeField;
        private List<SignerenoAddonservicesModelsGeneratedCodeForetakinfoNokkeltallKonsern> nokkeltallKonsernField;
        private SignerenoAddonservicesModelsGeneratedCodeForetakinfoBetaSammendrag betaSammendragField;
        private List<SignerenoAddonservicesModelsGeneratedCodeForetakinfoBetaDetaljer> betaDetaljerField;
        private List<SignerenoAddonservicesModelsGeneratedCodeForetakinfoLosore> losoreField;
        private SignerenoAddonservicesModelsGeneratedCodeForetakinfoEiendomNorge eiendomNorgeField;
        private List<SignerenoAddonservicesModelsGeneratedCodeForetakinfoKonsernLink> konsernLinkField;
        private SignerenoAddonservicesModelsGeneratedCodeForetakinfoScoring scoringField;
        private List<SignerenoAddonservicesModelsGeneratedCodeForetakinfoOkonomiSammendragForetak> okonomiSammendragForetakField;
        private List<SignerenoAddonservicesModelsGeneratedCodeForetakinfoOkonomiSammendragKonsern> okonomiSammendragKonsernField;
        private List<SignerenoAddonservicesModelsGeneratedCodeForetakinfoOkonomiDetaljerForetak> okonomiDetaljerForetakField;
        private List<SignerenoAddonservicesModelsGeneratedCodeForetakinfoOkonomiDetaljerKonsern> okonomiDetaljerKonsernField;
        private List<SignerenoAddonservicesModelsGeneratedCodeForetakinfoEiendelerForetak> eiendelerForetakField;
        private List<SignerenoAddonservicesModelsGeneratedCodeForetakinfoEiendelerKonsern> eiendelerKonsernField;
        private List<SignerenoAddonservicesModelsGeneratedCodeForetakinfoGjeldEgenkapitalForetak> gjeldEgenkapitalForetakField;
        private List<SignerenoAddonservicesModelsGeneratedCodeForetakinfoGjeldEgenkapitalKonsern> gjeldEgenkapitalKonsernField;
        private SignerenoAddonservicesModelsGeneratedCodeForetakinfoAvdelingData avdelingDataField;
        private List<SignerenoAddonservicesModelsGeneratedCodeForetakinfoRettighetshavere> rettighetshavereField;
        private List<SignerenoAddonservicesModelsGeneratedCodeForetakinfoEiendomNorgeListe> eiendomNorgeListeField;
        private List<SignerenoAddonservicesModelsGeneratedCodeForetakinfoFullmaktForetak> fullmaktForetakField;
        private List<SignerenoAddonservicesModelsGeneratedCodeForetakinfoMeldinger> meldingerField;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("identifikasjonField")]
        public SignerenoAddonservicesModelsGeneratedCodeForetakinfoIdentifikasjon IdentifikasjonField 
        { 
            get 
            {
                return this.identifikasjonField; 
            } 
            set 
            {
                this.identifikasjonField = value;
                onPropertyChanged("IdentifikasjonField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("navnAdresseField")]
        public SignerenoAddonservicesModelsGeneratedCodeForetakinfoNavnAdresse NavnAdresseField 
        { 
            get 
            {
                return this.navnAdresseField; 
            } 
            set 
            {
                this.navnAdresseField = value;
                onPropertyChanged("NavnAdresseField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("ratingField")]
        public SignerenoAddonservicesModelsGeneratedCodeForetakinfoRating RatingField 
        { 
            get 
            {
                return this.ratingField; 
            } 
            set 
            {
                this.ratingField = value;
                onPropertyChanged("RatingField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("histRatingField")]
        public List<SignerenoAddonservicesModelsGeneratedCodeForetakinfoHistoriskRating> HistRatingField 
        { 
            get 
            {
                return this.histRatingField; 
            } 
            set 
            {
                this.histRatingField = value;
                onPropertyChanged("HistRatingField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("grunnfaktaField")]
        public SignerenoAddonservicesModelsGeneratedCodeForetakinfoGrunnfakta GrunnfaktaField 
        { 
            get 
            {
                return this.grunnfaktaField; 
            } 
            set 
            {
                this.grunnfaktaField = value;
                onPropertyChanged("GrunnfaktaField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("juridiskField")]
        public List<SignerenoAddonservicesModelsGeneratedCodeForetakinfoJuridisk> JuridiskField 
        { 
            get 
            {
                return this.juridiskField; 
            } 
            set 
            {
                this.juridiskField = value;
                onPropertyChanged("JuridiskField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("vervField")]
        public List<SignerenoAddonservicesModelsGeneratedCodeForetakinfoVerv> VervField 
        { 
            get 
            {
                return this.vervField; 
            } 
            set 
            {
                this.vervField = value;
                onPropertyChanged("VervField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("aksjonarField")]
        public List<SignerenoAddonservicesModelsGeneratedCodeForetakinfoAksjonar> AksjonarField 
        { 
            get 
            {
                return this.aksjonarField; 
            } 
            set 
            {
                this.aksjonarField = value;
                onPropertyChanged("AksjonarField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("datterselskapField")]
        public List<SignerenoAddonservicesModelsGeneratedCodeForetakinfoDatterselskap> DatterselskapField 
        { 
            get 
            {
                return this.datterselskapField; 
            } 
            set 
            {
                this.datterselskapField = value;
                onPropertyChanged("DatterselskapField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("okonomiEnkField")]
        public List<SignerenoAddonservicesModelsGeneratedCodeForetakinfoOkonomiEnk> OkonomiEnkField 
        { 
            get 
            {
                return this.okonomiEnkField; 
            } 
            set 
            {
                this.okonomiEnkField = value;
                onPropertyChanged("OkonomiEnkField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("nokkeltallForetakField")]
        public List<SignerenoAddonservicesModelsGeneratedCodeForetakinfoNokkeltallForetak> NokkeltallForetakField 
        { 
            get 
            {
                return this.nokkeltallForetakField; 
            } 
            set 
            {
                this.nokkeltallForetakField = value;
                onPropertyChanged("NokkeltallForetakField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("nokkeltallBransjeField")]
        public List<SignerenoAddonservicesModelsGeneratedCodeForetakinfoNokkeltallBransje> NokkeltallBransjeField 
        { 
            get 
            {
                return this.nokkeltallBransjeField; 
            } 
            set 
            {
                this.nokkeltallBransjeField = value;
                onPropertyChanged("NokkeltallBransjeField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("nokkeltallKonsernField")]
        public List<SignerenoAddonservicesModelsGeneratedCodeForetakinfoNokkeltallKonsern> NokkeltallKonsernField 
        { 
            get 
            {
                return this.nokkeltallKonsernField; 
            } 
            set 
            {
                this.nokkeltallKonsernField = value;
                onPropertyChanged("NokkeltallKonsernField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("betaSammendragField")]
        public SignerenoAddonservicesModelsGeneratedCodeForetakinfoBetaSammendrag BetaSammendragField 
        { 
            get 
            {
                return this.betaSammendragField; 
            } 
            set 
            {
                this.betaSammendragField = value;
                onPropertyChanged("BetaSammendragField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("betaDetaljerField")]
        public List<SignerenoAddonservicesModelsGeneratedCodeForetakinfoBetaDetaljer> BetaDetaljerField 
        { 
            get 
            {
                return this.betaDetaljerField; 
            } 
            set 
            {
                this.betaDetaljerField = value;
                onPropertyChanged("BetaDetaljerField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("losoreField")]
        public List<SignerenoAddonservicesModelsGeneratedCodeForetakinfoLosore> LosoreField 
        { 
            get 
            {
                return this.losoreField; 
            } 
            set 
            {
                this.losoreField = value;
                onPropertyChanged("LosoreField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("eiendomNorgeField")]
        public SignerenoAddonservicesModelsGeneratedCodeForetakinfoEiendomNorge EiendomNorgeField 
        { 
            get 
            {
                return this.eiendomNorgeField; 
            } 
            set 
            {
                this.eiendomNorgeField = value;
                onPropertyChanged("EiendomNorgeField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("konsernLinkField")]
        public List<SignerenoAddonservicesModelsGeneratedCodeForetakinfoKonsernLink> KonsernLinkField 
        { 
            get 
            {
                return this.konsernLinkField; 
            } 
            set 
            {
                this.konsernLinkField = value;
                onPropertyChanged("KonsernLinkField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("scoringField")]
        public SignerenoAddonservicesModelsGeneratedCodeForetakinfoScoring ScoringField 
        { 
            get 
            {
                return this.scoringField; 
            } 
            set 
            {
                this.scoringField = value;
                onPropertyChanged("ScoringField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("okonomiSammendragForetakField")]
        public List<SignerenoAddonservicesModelsGeneratedCodeForetakinfoOkonomiSammendragForetak> OkonomiSammendragForetakField 
        { 
            get 
            {
                return this.okonomiSammendragForetakField; 
            } 
            set 
            {
                this.okonomiSammendragForetakField = value;
                onPropertyChanged("OkonomiSammendragForetakField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("okonomiSammendragKonsernField")]
        public List<SignerenoAddonservicesModelsGeneratedCodeForetakinfoOkonomiSammendragKonsern> OkonomiSammendragKonsernField 
        { 
            get 
            {
                return this.okonomiSammendragKonsernField; 
            } 
            set 
            {
                this.okonomiSammendragKonsernField = value;
                onPropertyChanged("OkonomiSammendragKonsernField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("okonomiDetaljerForetakField")]
        public List<SignerenoAddonservicesModelsGeneratedCodeForetakinfoOkonomiDetaljerForetak> OkonomiDetaljerForetakField 
        { 
            get 
            {
                return this.okonomiDetaljerForetakField; 
            } 
            set 
            {
                this.okonomiDetaljerForetakField = value;
                onPropertyChanged("OkonomiDetaljerForetakField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("okonomiDetaljerKonsernField")]
        public List<SignerenoAddonservicesModelsGeneratedCodeForetakinfoOkonomiDetaljerKonsern> OkonomiDetaljerKonsernField 
        { 
            get 
            {
                return this.okonomiDetaljerKonsernField; 
            } 
            set 
            {
                this.okonomiDetaljerKonsernField = value;
                onPropertyChanged("OkonomiDetaljerKonsernField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("eiendelerForetakField")]
        public List<SignerenoAddonservicesModelsGeneratedCodeForetakinfoEiendelerForetak> EiendelerForetakField 
        { 
            get 
            {
                return this.eiendelerForetakField; 
            } 
            set 
            {
                this.eiendelerForetakField = value;
                onPropertyChanged("EiendelerForetakField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("eiendelerKonsernField")]
        public List<SignerenoAddonservicesModelsGeneratedCodeForetakinfoEiendelerKonsern> EiendelerKonsernField 
        { 
            get 
            {
                return this.eiendelerKonsernField; 
            } 
            set 
            {
                this.eiendelerKonsernField = value;
                onPropertyChanged("EiendelerKonsernField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("gjeldEgenkapitalForetakField")]
        public List<SignerenoAddonservicesModelsGeneratedCodeForetakinfoGjeldEgenkapitalForetak> GjeldEgenkapitalForetakField 
        { 
            get 
            {
                return this.gjeldEgenkapitalForetakField; 
            } 
            set 
            {
                this.gjeldEgenkapitalForetakField = value;
                onPropertyChanged("GjeldEgenkapitalForetakField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("gjeldEgenkapitalKonsernField")]
        public List<SignerenoAddonservicesModelsGeneratedCodeForetakinfoGjeldEgenkapitalKonsern> GjeldEgenkapitalKonsernField 
        { 
            get 
            {
                return this.gjeldEgenkapitalKonsernField; 
            } 
            set 
            {
                this.gjeldEgenkapitalKonsernField = value;
                onPropertyChanged("GjeldEgenkapitalKonsernField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("avdelingDataField")]
        public SignerenoAddonservicesModelsGeneratedCodeForetakinfoAvdelingData AvdelingDataField 
        { 
            get 
            {
                return this.avdelingDataField; 
            } 
            set 
            {
                this.avdelingDataField = value;
                onPropertyChanged("AvdelingDataField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("rettighetshavereField")]
        public List<SignerenoAddonservicesModelsGeneratedCodeForetakinfoRettighetshavere> RettighetshavereField 
        { 
            get 
            {
                return this.rettighetshavereField; 
            } 
            set 
            {
                this.rettighetshavereField = value;
                onPropertyChanged("RettighetshavereField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("eiendomNorgeListeField")]
        public List<SignerenoAddonservicesModelsGeneratedCodeForetakinfoEiendomNorgeListe> EiendomNorgeListeField 
        { 
            get 
            {
                return this.eiendomNorgeListeField; 
            } 
            set 
            {
                this.eiendomNorgeListeField = value;
                onPropertyChanged("EiendomNorgeListeField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("fullmaktForetakField")]
        public List<SignerenoAddonservicesModelsGeneratedCodeForetakinfoFullmaktForetak> FullmaktForetakField 
        { 
            get 
            {
                return this.fullmaktForetakField; 
            } 
            set 
            {
                this.fullmaktForetakField = value;
                onPropertyChanged("FullmaktForetakField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("meldingerField")]
        public List<SignerenoAddonservicesModelsGeneratedCodeForetakinfoMeldinger> MeldingerField 
        { 
            get 
            {
                return this.meldingerField; 
            } 
            set 
            {
                this.meldingerField = value;
                onPropertyChanged("MeldingerField");
            }
        }

        /// <summary>
        /// Property changed event for observer pattern
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises event when a property is changed
        /// </summary>
        /// <param name="propertyName">Name of the changed property</param>
        protected void onPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
} 