/*
 * SignerenoAddonServices.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/10/2016
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SignerenoAddonServices.PCL;
using SignerenoAddonServices.PCL.Utilities;

namespace SignerenoAddonServices.PCL.Models
{
    public class SignerenoAddonservicesModelsGeneratedCodePersonInfoHentPersonResponse : INotifyPropertyChanged 
    {
        // These fields hold the values for the public properties.
        private SignerenoAddonservicesModelsGeneratedCodePersonInfoIdentifikasjon identifikasjonField;
        private SignerenoAddonservicesModelsGeneratedCodePersonInfoNavnAdresse navnAdresseField;
        private SignerenoAddonservicesModelsGeneratedCodePersonInfoScoring scoringField;
        private List<SignerenoAddonservicesModelsGeneratedCodePersonInfoDelomrader> delomraderField;
        private SignerenoAddonservicesModelsGeneratedCodePersonInfoBetaSammendrag betaSammendragField;
        private List<SignerenoAddonservicesModelsGeneratedCodePersonInfoBetaDetaljer> betaDetaljerField;
        private List<SignerenoAddonservicesModelsGeneratedCodePersonInfoLigning> ligningField;
        private List<SignerenoAddonservicesModelsGeneratedCodePersonInfoDisponibelInntekt> disponibelInntektField;
        private List<SignerenoAddonservicesModelsGeneratedCodePersonInfoNaringsInteresser> naringsInteresserField;
        private SignerenoAddonservicesModelsGeneratedCodePersonInfoEiendomNorge eiendomNorgeField;
        private List<SignerenoAddonservicesModelsGeneratedCodePersonInfoEiendomListe> eiendomListeField;
        private List<SignerenoAddonservicesModelsGeneratedCodePersonInfoLosore> losoreField;
        private List<SignerenoAddonservicesModelsGeneratedCodePersonInfoTidligereNavnAdresse> tidligereNavnAdresseField;
        private List<SignerenoAddonservicesModelsGeneratedCodePersonInfoFullmaktForetak> fullmaktForetakField;
        private List<SignerenoAddonservicesModelsGeneratedCodePersonInfoMeldinger> meldingerField;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("identifikasjonField")]
        public SignerenoAddonservicesModelsGeneratedCodePersonInfoIdentifikasjon IdentifikasjonField 
        { 
            get 
            {
                return this.identifikasjonField; 
            } 
            set 
            {
                this.identifikasjonField = value;
                onPropertyChanged("IdentifikasjonField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("navnAdresseField")]
        public SignerenoAddonservicesModelsGeneratedCodePersonInfoNavnAdresse NavnAdresseField 
        { 
            get 
            {
                return this.navnAdresseField; 
            } 
            set 
            {
                this.navnAdresseField = value;
                onPropertyChanged("NavnAdresseField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("scoringField")]
        public SignerenoAddonservicesModelsGeneratedCodePersonInfoScoring ScoringField 
        { 
            get 
            {
                return this.scoringField; 
            } 
            set 
            {
                this.scoringField = value;
                onPropertyChanged("ScoringField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("delomraderField")]
        public List<SignerenoAddonservicesModelsGeneratedCodePersonInfoDelomrader> DelomraderField 
        { 
            get 
            {
                return this.delomraderField; 
            } 
            set 
            {
                this.delomraderField = value;
                onPropertyChanged("DelomraderField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("betaSammendragField")]
        public SignerenoAddonservicesModelsGeneratedCodePersonInfoBetaSammendrag BetaSammendragField 
        { 
            get 
            {
                return this.betaSammendragField; 
            } 
            set 
            {
                this.betaSammendragField = value;
                onPropertyChanged("BetaSammendragField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("betaDetaljerField")]
        public List<SignerenoAddonservicesModelsGeneratedCodePersonInfoBetaDetaljer> BetaDetaljerField 
        { 
            get 
            {
                return this.betaDetaljerField; 
            } 
            set 
            {
                this.betaDetaljerField = value;
                onPropertyChanged("BetaDetaljerField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("ligningField")]
        public List<SignerenoAddonservicesModelsGeneratedCodePersonInfoLigning> LigningField 
        { 
            get 
            {
                return this.ligningField; 
            } 
            set 
            {
                this.ligningField = value;
                onPropertyChanged("LigningField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("disponibelInntektField")]
        public List<SignerenoAddonservicesModelsGeneratedCodePersonInfoDisponibelInntekt> DisponibelInntektField 
        { 
            get 
            {
                return this.disponibelInntektField; 
            } 
            set 
            {
                this.disponibelInntektField = value;
                onPropertyChanged("DisponibelInntektField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("naringsInteresserField")]
        public List<SignerenoAddonservicesModelsGeneratedCodePersonInfoNaringsInteresser> NaringsInteresserField 
        { 
            get 
            {
                return this.naringsInteresserField; 
            } 
            set 
            {
                this.naringsInteresserField = value;
                onPropertyChanged("NaringsInteresserField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("eiendomNorgeField")]
        public SignerenoAddonservicesModelsGeneratedCodePersonInfoEiendomNorge EiendomNorgeField 
        { 
            get 
            {
                return this.eiendomNorgeField; 
            } 
            set 
            {
                this.eiendomNorgeField = value;
                onPropertyChanged("EiendomNorgeField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("eiendomListeField")]
        public List<SignerenoAddonservicesModelsGeneratedCodePersonInfoEiendomListe> EiendomListeField 
        { 
            get 
            {
                return this.eiendomListeField; 
            } 
            set 
            {
                this.eiendomListeField = value;
                onPropertyChanged("EiendomListeField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("losoreField")]
        public List<SignerenoAddonservicesModelsGeneratedCodePersonInfoLosore> LosoreField 
        { 
            get 
            {
                return this.losoreField; 
            } 
            set 
            {
                this.losoreField = value;
                onPropertyChanged("LosoreField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("tidligereNavnAdresseField")]
        public List<SignerenoAddonservicesModelsGeneratedCodePersonInfoTidligereNavnAdresse> TidligereNavnAdresseField 
        { 
            get 
            {
                return this.tidligereNavnAdresseField; 
            } 
            set 
            {
                this.tidligereNavnAdresseField = value;
                onPropertyChanged("TidligereNavnAdresseField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("fullmaktForetakField")]
        public List<SignerenoAddonservicesModelsGeneratedCodePersonInfoFullmaktForetak> FullmaktForetakField 
        { 
            get 
            {
                return this.fullmaktForetakField; 
            } 
            set 
            {
                this.fullmaktForetakField = value;
                onPropertyChanged("FullmaktForetakField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("meldingerField")]
        public List<SignerenoAddonservicesModelsGeneratedCodePersonInfoMeldinger> MeldingerField 
        { 
            get 
            {
                return this.meldingerField; 
            } 
            set 
            {
                this.meldingerField = value;
                onPropertyChanged("MeldingerField");
            }
        }

        /// <summary>
        /// Property changed event for observer pattern
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises event when a property is changed
        /// </summary>
        /// <param name="propertyName">Name of the changed property</param>
        protected void onPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
} 