/*
 * SignerenoAddonServices.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/10/2016
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SignerenoAddonServices.PCL;
using SignerenoAddonServices.PCL.Utilities;

namespace SignerenoAddonServices.PCL.Models
{
    public class SignerenoAddonservicesModelsGeneratedCodeForetakinfoVerv : INotifyPropertyChanged 
    {
        // These fields hold the values for the public properties.
        private long? internRefField;
        private DateTime? fodtDatoField;
        private bool? fodtDatoFieldSpecified;
        private string navnField;
        private List<string> telefonField;
        private int? postnrField;
        private string poststedField;
        private string vervKodeField;
        private string vervTekstField;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("internRefField")]
        public long? InternRefField 
        { 
            get 
            {
                return this.internRefField; 
            } 
            set 
            {
                this.internRefField = value;
                onPropertyChanged("InternRefField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("fodtDatoField")]
        public DateTime? FodtDatoField 
        { 
            get 
            {
                return this.fodtDatoField; 
            } 
            set 
            {
                this.fodtDatoField = value;
                onPropertyChanged("FodtDatoField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("fodtDatoFieldSpecified")]
        public bool? FodtDatoFieldSpecified 
        { 
            get 
            {
                return this.fodtDatoFieldSpecified; 
            } 
            set 
            {
                this.fodtDatoFieldSpecified = value;
                onPropertyChanged("FodtDatoFieldSpecified");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("navnField")]
        public string NavnField 
        { 
            get 
            {
                return this.navnField; 
            } 
            set 
            {
                this.navnField = value;
                onPropertyChanged("NavnField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("telefonField")]
        public List<string> TelefonField 
        { 
            get 
            {
                return this.telefonField; 
            } 
            set 
            {
                this.telefonField = value;
                onPropertyChanged("TelefonField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("postnrField")]
        public int? PostnrField 
        { 
            get 
            {
                return this.postnrField; 
            } 
            set 
            {
                this.postnrField = value;
                onPropertyChanged("PostnrField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("poststedField")]
        public string PoststedField 
        { 
            get 
            {
                return this.poststedField; 
            } 
            set 
            {
                this.poststedField = value;
                onPropertyChanged("PoststedField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("vervKodeField")]
        public string VervKodeField 
        { 
            get 
            {
                return this.vervKodeField; 
            } 
            set 
            {
                this.vervKodeField = value;
                onPropertyChanged("VervKodeField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("vervTekstField")]
        public string VervTekstField 
        { 
            get 
            {
                return this.vervTekstField; 
            } 
            set 
            {
                this.vervTekstField = value;
                onPropertyChanged("VervTekstField");
            }
        }

        /// <summary>
        /// Property changed event for observer pattern
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises event when a property is changed
        /// </summary>
        /// <param name="propertyName">Name of the changed property</param>
        protected void onPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
} 