/*
 * SignerenoAddonServices.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/10/2016
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SignerenoAddonServices.PCL;
using SignerenoAddonServices.PCL.Utilities;

namespace SignerenoAddonServices.PCL.Models
{
    public class SignerenoAddonservicesModelsGeneratedCodeForetakinfoNavnAdresse : INotifyPropertyChanged 
    {
        // These fields hold the values for the public properties.
        private string kodeTypeField;
        private string kodeTekstField;
        private string navnField;
        private string gateAdresseField;
        private int? gatePostboksField;
        private int? gatePostnrField;
        private string gatePoststedField;
        private string postAdresseField;
        private int? postPostboksField;
        private int? postPostnrField;
        private string postPoststedField;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("kodeTypeField")]
        public string KodeTypeField 
        { 
            get 
            {
                return this.kodeTypeField; 
            } 
            set 
            {
                this.kodeTypeField = value;
                onPropertyChanged("KodeTypeField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("kodeTekstField")]
        public string KodeTekstField 
        { 
            get 
            {
                return this.kodeTekstField; 
            } 
            set 
            {
                this.kodeTekstField = value;
                onPropertyChanged("KodeTekstField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("navnField")]
        public string NavnField 
        { 
            get 
            {
                return this.navnField; 
            } 
            set 
            {
                this.navnField = value;
                onPropertyChanged("NavnField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("gateAdresseField")]
        public string GateAdresseField 
        { 
            get 
            {
                return this.gateAdresseField; 
            } 
            set 
            {
                this.gateAdresseField = value;
                onPropertyChanged("GateAdresseField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("gatePostboksField")]
        public int? GatePostboksField 
        { 
            get 
            {
                return this.gatePostboksField; 
            } 
            set 
            {
                this.gatePostboksField = value;
                onPropertyChanged("GatePostboksField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("gatePostnrField")]
        public int? GatePostnrField 
        { 
            get 
            {
                return this.gatePostnrField; 
            } 
            set 
            {
                this.gatePostnrField = value;
                onPropertyChanged("GatePostnrField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("gatePoststedField")]
        public string GatePoststedField 
        { 
            get 
            {
                return this.gatePoststedField; 
            } 
            set 
            {
                this.gatePoststedField = value;
                onPropertyChanged("GatePoststedField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("postAdresseField")]
        public string PostAdresseField 
        { 
            get 
            {
                return this.postAdresseField; 
            } 
            set 
            {
                this.postAdresseField = value;
                onPropertyChanged("PostAdresseField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("postPostboksField")]
        public int? PostPostboksField 
        { 
            get 
            {
                return this.postPostboksField; 
            } 
            set 
            {
                this.postPostboksField = value;
                onPropertyChanged("PostPostboksField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("postPostnrField")]
        public int? PostPostnrField 
        { 
            get 
            {
                return this.postPostnrField; 
            } 
            set 
            {
                this.postPostnrField = value;
                onPropertyChanged("PostPostnrField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("postPoststedField")]
        public string PostPoststedField 
        { 
            get 
            {
                return this.postPoststedField; 
            } 
            set 
            {
                this.postPoststedField = value;
                onPropertyChanged("PostPoststedField");
            }
        }

        /// <summary>
        /// Property changed event for observer pattern
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises event when a property is changed
        /// </summary>
        /// <param name="propertyName">Name of the changed property</param>
        protected void onPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
} 