/*
 * SignerenoAddonServices.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/10/2016
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SignerenoAddonServices.PCL;
using SignerenoAddonServices.PCL.Utilities;

namespace SignerenoAddonServices.PCL.Models
{
    public class SignerenoAddonservicesModelsGeneratedCodeForetakinfoKonsernLink : INotifyPropertyChanged 
    {
        // These fields hold the values for the public properties.
        private int? orgnrOversteMorField;
        private int? orgnrNaermesteMorField;
        private int? lopenrField;
        private int? nivaDeltagendeField;
        private string landkodeDeltagendeField;
        private int? orgnrDeltagendeField;
        private string navnDeltagendeField;
        private double? eierandelDeltagendeField;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("orgnrOversteMorField")]
        public int? OrgnrOversteMorField 
        { 
            get 
            {
                return this.orgnrOversteMorField; 
            } 
            set 
            {
                this.orgnrOversteMorField = value;
                onPropertyChanged("OrgnrOversteMorField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("orgnrNaermesteMorField")]
        public int? OrgnrNaermesteMorField 
        { 
            get 
            {
                return this.orgnrNaermesteMorField; 
            } 
            set 
            {
                this.orgnrNaermesteMorField = value;
                onPropertyChanged("OrgnrNaermesteMorField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("lopenrField")]
        public int? LopenrField 
        { 
            get 
            {
                return this.lopenrField; 
            } 
            set 
            {
                this.lopenrField = value;
                onPropertyChanged("LopenrField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("nivaDeltagendeField")]
        public int? NivaDeltagendeField 
        { 
            get 
            {
                return this.nivaDeltagendeField; 
            } 
            set 
            {
                this.nivaDeltagendeField = value;
                onPropertyChanged("NivaDeltagendeField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("landkodeDeltagendeField")]
        public string LandkodeDeltagendeField 
        { 
            get 
            {
                return this.landkodeDeltagendeField; 
            } 
            set 
            {
                this.landkodeDeltagendeField = value;
                onPropertyChanged("LandkodeDeltagendeField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("orgnrDeltagendeField")]
        public int? OrgnrDeltagendeField 
        { 
            get 
            {
                return this.orgnrDeltagendeField; 
            } 
            set 
            {
                this.orgnrDeltagendeField = value;
                onPropertyChanged("OrgnrDeltagendeField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("navnDeltagendeField")]
        public string NavnDeltagendeField 
        { 
            get 
            {
                return this.navnDeltagendeField; 
            } 
            set 
            {
                this.navnDeltagendeField = value;
                onPropertyChanged("NavnDeltagendeField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("eierandelDeltagendeField")]
        public double? EierandelDeltagendeField 
        { 
            get 
            {
                return this.eierandelDeltagendeField; 
            } 
            set 
            {
                this.eierandelDeltagendeField = value;
                onPropertyChanged("EierandelDeltagendeField");
            }
        }

        /// <summary>
        /// Property changed event for observer pattern
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises event when a property is changed
        /// </summary>
        /// <param name="propertyName">Name of the changed property</param>
        protected void onPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
} 