/*
 * SignerenoAddonServices.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/10/2016
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SignerenoAddonServices.PCL;
using SignerenoAddonServices.PCL.Utilities;

namespace SignerenoAddonServices.PCL.Models
{
    public class SignerenoAddonservicesModelsGeneratedCodePersonInfoNaringsInteresser : INotifyPropertyChanged 
    {
        // These fields hold the values for the public properties.
        private int? orgnrField;
        private string statusKodeField;
        private string statusTekstField;
        private DateTime? statusDatoField;
        private string navnField;
        private string selskFormField;
        private string rolleField;
        private double? eierandelField;
        private string vervKodeField;
        private string vervTekstField;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("orgnrField")]
        public int? OrgnrField 
        { 
            get 
            {
                return this.orgnrField; 
            } 
            set 
            {
                this.orgnrField = value;
                onPropertyChanged("OrgnrField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("statusKodeField")]
        public string StatusKodeField 
        { 
            get 
            {
                return this.statusKodeField; 
            } 
            set 
            {
                this.statusKodeField = value;
                onPropertyChanged("StatusKodeField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("statusTekstField")]
        public string StatusTekstField 
        { 
            get 
            {
                return this.statusTekstField; 
            } 
            set 
            {
                this.statusTekstField = value;
                onPropertyChanged("StatusTekstField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("statusDatoField")]
        public DateTime? StatusDatoField 
        { 
            get 
            {
                return this.statusDatoField; 
            } 
            set 
            {
                this.statusDatoField = value;
                onPropertyChanged("StatusDatoField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("navnField")]
        public string NavnField 
        { 
            get 
            {
                return this.navnField; 
            } 
            set 
            {
                this.navnField = value;
                onPropertyChanged("NavnField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("selskFormField")]
        public string SelskFormField 
        { 
            get 
            {
                return this.selskFormField; 
            } 
            set 
            {
                this.selskFormField = value;
                onPropertyChanged("SelskFormField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("rolleField")]
        public string RolleField 
        { 
            get 
            {
                return this.rolleField; 
            } 
            set 
            {
                this.rolleField = value;
                onPropertyChanged("RolleField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("eierandelField")]
        public double? EierandelField 
        { 
            get 
            {
                return this.eierandelField; 
            } 
            set 
            {
                this.eierandelField = value;
                onPropertyChanged("EierandelField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("vervKodeField")]
        public string VervKodeField 
        { 
            get 
            {
                return this.vervKodeField; 
            } 
            set 
            {
                this.vervKodeField = value;
                onPropertyChanged("VervKodeField");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("vervTekstField")]
        public string VervTekstField 
        { 
            get 
            {
                return this.vervTekstField; 
            } 
            set 
            {
                this.vervTekstField = value;
                onPropertyChanged("VervTekstField");
            }
        }

        /// <summary>
        /// Property changed event for observer pattern
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises event when a property is changed
        /// </summary>
        /// <param name="propertyName">Name of the changed property</param>
        protected void onPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
} 