/*
 * SignerenoAddonServices.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/10/2016
 */
using System;
using SignerenoAddonServices.PCL.Controllers;
using SignerenoAddonServices.PCL.Http.Client;

namespace SignerenoAddonServices.PCL
{
    public partial class SignerenoAddonServicesClient
    {

        /// <summary>
        /// Singleton access to SignatureRolesCheck controller
        /// </summary>
        public SignatureRolesCheckController SignatureRolesCheck
        {
            get
            {
                return SignatureRolesCheckController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to OfficialPersonRegistry controller
        /// </summary>
        public OfficialPersonRegistryController OfficialPersonRegistry
        {
            get
            {
                return OfficialPersonRegistryController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to PersonalInfo controller
        /// </summary>
        public PersonalInfoController PersonalInfo
        {
            get
            {
                return PersonalInfoController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to CompanyInfo controller
        /// </summary>
        public CompanyInfoController CompanyInfo
        {
            get
            {
                return CompanyInfoController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to CreditCheck controller
        /// </summary>
        public CreditCheckController CreditCheck
        {
            get
            {
                return CreditCheckController.Instance;
            }
        }
        /// <summary>
        /// The shared http client to use for all API calls
        /// </summary>
        public IHttpClient SharedHttpClient
        {
            get
            {
                return BaseController.ClientInstance;
            }
            set
            {
                BaseController.ClientInstance = value;
            }        
        }
        
        /// <summary>
        /// Default constructor
        /// </summary>
        public SignerenoAddonServicesClient() { }

        /// <summary>
        /// Client initialization constructor
        /// </summary>
        public SignerenoAddonServicesClient(string oAuthAccessToken)
        {
            Configuration.OAuthAccessToken = oAuthAccessToken;
        }
    }
}